#实例名称
spring:
  application:
    name: eureka-zuul
#端口号
server:
  port: 8201

#服务注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

zuul:
  routes:
    order:
      path: /order/**
      serviceId: eureka-provider-order
    account:
      path: /account/**
      serviceId: eureka-provider-account
